backend = "glx";

shadow = true;
shadow-radius = 10;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.6;
shadow-red = 0.0;
shadow-blue = 0.0;

# Ensure no frame transparency
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.1;
fade-delta = 15;
no-fading-openclose = false;

corner-radius= 10.0

vsync = true;

animations = (
  {
    triggers = ["close","hide"];
    preset = "disappear"
    scale = 0.4
    opacity = {
      duration = 0.4;
      start = "window-raw-opacity-before";
      end = 0;
    };
  },
  {
    triggers = ["open","show"];
    opacity = {
      curve = "cubic-bezier(0.3,1.0,0.4,1)";
      duration = 0.4;
      start = 0;
      end = "window-raw-opacity";
    }
    offset-x = "(1 - scale-x) / 2 * window-width";
    offset-y = "(1 - scale-y) / 2 * window-height";
    scale-x = {
      curve = "cubic-bezier(0.3,1.0,0.4,1)";
      duration = 0.4;
      start = 0;
      end = 1;
    };
    scale-y = "scale-x";
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
  },
  {
    triggers = ["geometry"]
    scale-x = {
      curve = "cubic-bezier(0.3,1.0,0.4,1)";
      duration = 0.4;
      start = "window-width-before / window-width";
      end = 1;
    }
    scale-y = {
      curve = "cubic-bezier(0.3,1.0,0.4,1)";
      duration = 0.4;
      start = "window-height-before / window-height";
      end = 1;
    }
    offset-x = {
      curve = "cubic-bezier(0.3,1.0,0.4,1)";
      duration = 0.4;
      start = "window-x-before - window-x";
      end = 0;
    }
    offset-y = {
      curve = "cubic-bezier(0.3,1.0,0.4,1)";

      duration = 0.4;
      start = "window-y-before - window-y";
      end = 0;
    }

    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
  }
)
